apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: backend-assessment
    component: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-assessment
      component: auth
  template:
    metadata:
      labels:
        app: backend-assessment
        component: auth
    spec:
      containers:
        - name: auth
          image: auth-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: DB_HOST
              value: "db"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              value: "secret_123"
            - name: JWT_REFRESH_SECRET
              value: "refresh_secret_123"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: backend-assessment
    component: auth
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
  selector:
    app: backend-assessment
    component: auth
