apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  labels:
    app: backend-assessment
    component: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-assessment
      component: db
  template:
    metadata:
      labels:
        app: backend-assessment
        component: db
    spec:
      containers:
        - name: db
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: backend-assessment
    component: db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: backend-assessment
    component: db
