apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
  labels:
    app: backend-assessment
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-assessment
      component: frontend
  template:
    metadata:
      labels:
        app: backend-assessment
        component: frontend
    spec:
      containers:
        - name: frontend
          image: backend-intern-frontend:latest # Make sure to tag your image as this
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          env:
            - name: VITE_AUTH_API_URL
              value: "http://localhost:30008/api/v1" # Change localhost to your node IP if needed
            - name: VITE_TASK_API_URL
              value: "http://localhost:30009/api/v1" # Change localhost to your node IP if needed

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: backend-assessment
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30007 # Access via <NodeIP>:30007
  selector:
    app: backend-assessment
    component: frontend
